<?php
/**
 * Sample layout
 */

use Core\Language;

?>
	    <div class="page-header">
	            <h1>Voorwaarden</h1>
	    </div>
	    <p>
	    	<b>artikel 1.	Algemeen</b><br>
	    	Deze voorwaarden zijn van toepassing op iedere aanbieding, offerte en overeenkomst
	    	tussen …………………….., hierna te noemen: “Gebruiker”, en een Opdrachtgever waarop Gebruiker deze voorwaarden van toepassing heeft verklaard, voor zover van deze voorwaarden niet door partijen uitdrukkelijk en schriftelijk is afgeweken.
	    	De onderhavige voorwaarden zijn eveneens van toepassing op overeenkomsten met Gebruiker, voor de uitvoering waarvan door Gebruiker derden dienen te worden betrokken.
	    	Deze algemene voorwaarden zijn eveneens geschreven voor de medewerkers van Gebruiker en zijn directie.
	    	De toepasselijkheid van eventuele inkoop­ of andere voorwaarden van Opdrachtgever wordt uitdrukkelijk van de hand gewezen.
	    	Indien één of meerdere bepalingen in deze algemene voorwaarden op enig moment geheel of gedeeltelijk nietig zijn of vernietigd mochten worden, dan blijft het overigens in deze algemene voorwaarden bepaalde volledig van toepassing. Gebruiker en de Opdrachtgever zullen alsdan in overleg treden teneinde nieuwe bepalingen ter vervanging van de nietige of vernietigde bepalingen overeen te komen, waarbij zoveel als mogelijk het doel en de strekking van de oorspronkelijke bepalingen in acht wordt genomen.
	    	Indien onduidelijkheid bestaat omtrent de uitleg van één of meerdere bepalingen van deze algemene voorwaarden, dan dient de uitleg plaats te vinden ‘naar de geest’ van deze bepalingen.
	    	Indien zich tussen partijen een situatie voordoet die niet in deze algemene voorwaarden geregeld is, dan dient deze situatie te worden beoordeeld naar de geest van deze algemene voorwaarden.
	    	Indien Gebruiker niet steeds strikte naleving van deze voorwaarden verlangt, betekent dit niet dat de bepalingen daarvan niet van toepassing zijn, of dat Gebruiker in enigerlei mate het recht zou verliezen om in andere gevallen de stipte naleving van de bepalingen van deze voorwaarden te verlangen.
	    	<br><br>
	    	<b>artikel 2 	Offertes en aanbiedingen</b><br>
	    	Alle offertes en aanbiedingen van Gebruiker zijn vrijblijvend, tenzij in de offerte een termijn voor aanvaarding is gesteld. Indien geen aanvaardingstermijn is gesteld, kan aan de offerte of aanbieding op generlei wijze enig recht worden ontleend indien het product waarop de offerte of de aanbieding betrekking heeft in de tussentijd niet meer beschikbaar is. 
	    	Gebruiker kan niet aan zijn offertes of aanbiedingen worden gehouden indien de Opdrachtgever redelijkerwijs kan begrijpen dat de offertes of aanbiedingen, dan wel een onderdeel daarvan, een kennelijke vergissing of verschrijving bevat.
	    	De in een offerte of aanbieding vermelde prijzen zijn exclusief BTW en andere heffingen van overheidswege, eventuele in het kader van de overeenkomst te maken kosten, daaronder begrepen reis- en verblijf-, verzend- en administratiekosten, tenzij anders aangegeven.
	    	Indien de aanvaarding (al dan niet op ondergeschikte punten) afwijkt van het in de offerte of de aanbieding opgenomen aanbod dan is Gebruiker daaraan niet gebonden. De overeenkomst komt dan niet overeenkomstig deze afwijkende aanvaarding tot stand, tenzij Gebruiker anders aangeeft.
	    	Een samengestelde prijsopgave verplicht Gebruiker niet tot het verrichten van een gedeelte van de opdracht tegen een overeenkomstig deel van de opgegeven prijs. Aanbiedingen of offertes gelden niet automatisch voor toekomstige orders. 
			<br><br>
	    	<b>artikel 3 	Contractsduur; uitvoeringstermijnen, risico-overgang, uitvoering en wijziging overeenkomst; prijsverhoging</b><br>
	    	De overeenkomst tussen Gebruiker en de Opdrachtgever wordt aangegaan voor onbepaalde tijd, tenzij uit de aard van de overeenkomst anders voortvloeit of indien partijen uitdrukkelijk en schriftelijk anders overeenkomen.
	    	Is voor de uitvoering van bepaalde werkzaamheden of voor de levering van bepaalde zaken een termijn overeengekomen of opgegeven, dan is dit nimmer een fatale termijn. Bij overschrijding van een termijn dient de Opdrachtgever Gebruiker derhalve schriftelijk in gebreke te stellen. Gebruiker dient daarbij een redelijke termijn te worden geboden om alsnog uitvoering te geven aan de overeenkomst.
	    	Gebruiker zal de overeenkomst naar beste inzicht en vermogen en overeenkomstig de eisen van goed vakmanschap uitvoeren. Een en ander op grond van de op dat moment bekende stand der wetenschap. 
	    	Gebruiker heeft het recht bepaalde werkzaamheden te laten verrichten door derden. De toepasselijkheid van artikel 7:404, 7:407 lid 2 en 7:409 BW wordt uitdrukkelijk uitgesloten.
	    	Indien door Gebruiker of door Gebruiker ingeschakelde derden in het kader van de opdracht werkzaamheden worden verricht op de locatie van de Opdrachtgever of een door de Opdrachtgever aangewezen locatie, draagt de Opdrachtgever kosteloos zorg voor de door die medewerkers in redelijkheid gewenste faciliteiten. 
	    	Levering geschiedt af bedrijf van Gebruiker. De Opdrachtgever is verplicht de zaken af te nemen op het moment dat deze hem ter beschikking worden gesteld. Indien de Opdrachtgever afname weigert of nalatig is met het verstrekken van informatie of instructies die noodzakelijk zijn voor de levering, dan is Gebruiker gerechtigd de zaken op te slaan voor rekening en risico van de Opdrachtgever. Het risico van verlies, beschadiging of waardevermindering gaat op de Opdrachtgever over op het moment waarop zaken aan de Opdrachtgever ter beschikking staan.
	    	Gebruiker is gerechtigd de overeenkomst in verschillende fasen uit te voeren en het aldus uitgevoerde gedeelte afzonderlijk te factureren. 
	    	Indien de overeenkomst in fasen wordt uitgevoerd kan Gebruiker de uitvoering van die onderdelen die tot een volgende fase behoren opschorten totdat de Opdrachtgever de resultaten van de daaraan voorafgaande fase schriftelijk heeft goedgekeurd. 
	    	De Opdrachtgever draagt er zorg voor dat alle gegevens, waarvan Gebruiker aangeeft dat deze noodzakelijk zijn of waarvan de Opdrachtgever redelijkerwijs behoort te begrijpen dat deze noodzakelijk zijn voor het uitvoeren van de overeenkomst, tijdig aan Gebruiker worden verstrekt. Indien de voor de uitvoering van de overeenkomst benodigde gegevens niet tijdig aan Gebruiker zijn verstrekt, heeft Gebruiker het recht de uitvoering van de overeenkomst op te schorten en / of de uit de vertraging voortvloeiende extra kosten volgens de alsdan gebruikelijke tarieven aan de Opdrachtgever in rekening te brengen. De uitvoeringstermijn vangt niet eerder aan dan nadat de Opdrachtgever de gegevens aan Gebruiker ter beschikking heeft gesteld. Gebruiker is niet aansprakelijk voor schade, van welke aard ook, doordat Gebruiker is uitgegaan van door de Opdrachtgever verstrekte onjuiste en / of onvolledige gegevens.
	    	Indien tijdens de uitvoering van de overeenkomst blijkt dat het voor een behoorlijke uitvoering daarvan noodzakelijk is om deze te wijzigen of aan te vullen, dan zullen partijen tijdig en in onderling overleg tot aanpassing van de overeenkomst overgaan. Indien de aard, omvang of inhoud van de overeenkomst, al dan niet op verzoek of aanwijzing van de Opdrachtgever, van de bevoegde instanties et cetera, wordt gewijzigd en de overeenkomst daardoor in kwalitatief en / of kwantitatief opzicht wordt gewijzigd, dan kan dit consequenties hebben voor hetgeen oorspronkelijk overeengekomen werd. Daardoor kan ook het oorspronkelijk overeengekomen bedrag worden verhoogd of verlaagd. Gebruiker zal daarvan zoveel als mogelijk vooraf prijsopgaaf doen. Door een wijziging van de overeenkomst kan voorts de oorspronkelijk opgegeven termijn van uitvoering worden gewijzigd. De Opdrachtgever aanvaardt de mogelijkheid van wijziging van de overeenkomst, daaronder begrepen de wijziging in prijs en termijn van uitvoering.
	    	Indien de overeenkomst wordt gewijzigd, daaronder begrepen een aanvulling, dan is Gebruiker gerechtigd om daaraan eerst uitvoering te geven nadat daarvoor akkoord is gegeven door de binnen Gebruiker bevoegde persoon en de Opdrachtgever akkoord is gegaan met de voor de uitvoering opgegeven prijs en andere voorwaarden, daaronder begrepen het alsdan te bepalen tijdstip waarop daaraan uitvoering gegeven zal worden. Het niet of niet onmiddellijk uitvoeren van de gewijzigde overeenkomst levert geen wanprestatie van Gebruiker op en is voor de Opdrachtgever geen grond om de overeenkomst op te zeggen of te annuleren.
	    	Zonder daarmee in gebreke te komen, kan Gebruiker een verzoek tot wijziging van de overeenkomst weigeren, indien dit in kwalitatief en / of kwantitatief opzicht gevolg zou kunnen hebben bijvoorbeeld voor de in dat kader te verrichten werkzaamheden of te leveren zaken.
	    	Indien de Opdrachtgever in gebreke mocht komen in de deugdelijke nakoming van hetgeen waartoe hij jegens Gebruiker gehouden is, dan is de Opdrachtgever aansprakelijk voor alle schade aan de zijde van Gebruiker daardoor direct of indirect ontstaan.
	    	Indien Gebruiker met de Opdrachtgever een vast honorarium of vaste prijs overeenkomt, dan is Gebruiker niettemin te allen tijde gerechtigd tot verhoging van dit honorarium of deze prijs zonder dat de Opdrachtgever in dat geval gerechtigd is om de overeenkomst om die reden te ontbinden, indien de verhoging van de prijs voortvloeit uit een bevoegdheid of verplichting ingevolge de wet- of regelgeving of haar oorzaak vindt in een stijging van de prijs van grondstoffen, lonen et cetera of op andere gronden die bij het aangaan van de overeenkomst redelijkerwijs niet voorzienbaar waren.
	    	Indien de prijsstijging anders dan als gevolg van een wijziging van de overeenkomst meer bedraagt dan 10% en plaatsvindt binnen drie maanden na het sluiten van de overeenkomst, dan is uitsluitend de Opdrachtgever die een beroep toekomt op titel 5 afdeling 3 van Boek 6 BW gerechtigd de overeenkomst door een schriftelijke verklaring te ontbinden, tenzij Gebruiker 
	    	alsdan alsnog bereid is om de overeenkomst op basis van het oorspronkelijk overeengekomene uit te voeren;
	    	indien de prijsverhoging voortvloeit uit een bevoegdheid of een op Gebruiker rustende verplichting ingevolge de wet; 
	    	indien bedongen is dat de aflevering langer dan drie maanden na de totstandkoming van de overeenkomst zal plaatsvinden;
	    	of, bij levering van een zaak, indien is bedongen dat de aflevering langer dan drie maanden na de koop zal plaatsvinden. 

	    </p>